import CoreColors from "./core-colors"
const Colors = {
    "color-text-default": CoreColors['base08'],
    "color-text-secondary": CoreColors['base07'],
    "color-text-inactive": CoreColors["base05"],
    "color-text-inverse": CoreColors["white"],
    "color-text-error": CoreColors["error06"],
    "color-text-warning": CoreColors["warning06"],
    "color-text-primary": CoreColors["primary06"],
    "color-text-info": CoreColors["info06"],
    "color-text-success": CoreColors["success06"],
    "color-text-placeholder": CoreColors["base04"],
    "color-border": CoreColors["base02"],
    "color-border-primary": CoreColors["primary06"],
    "color-border-error": CoreColors["error06"],
    "color-icon-inverse": CoreColors['white'],
    "color-icon-default": CoreColors["base06"],
    "color-icon-inactive": CoreColors["base05"],
    "color-icon-primary": CoreColors["primary06"],
    "color-background-titlebar": CoreColors["black"],
    "color-background-header": CoreColors["base08"],
    "color-background-base": CoreColors["base10"],
    "color-background-inactive": CoreColors["base02"],
    "color-background-section": CoreColors["base01"],
    "color-background-progressbar": CoreColors["base02"],
    "color-background-error": CoreColors["error06"],
    "color-background-success": CoreColors["success06"],
    "color-background-warning": CoreColors["warning06"],
    "color-background-section-warning": CoreColors["warning01"],
    "color-background-section-primary": CoreColors["primary01"],
    "color-background-section-error": CoreColors["error01"],
    "color-background-info": CoreColors["info08"],
    "color-background-white": CoreColors['white'],
    "color-background-button-hover": CoreColors["primary07"],
    "color-background-primary": CoreColors["primary06"],
    "color-highlight-progressbar": CoreColors["primary06"],
    "color-social-facebook": "#066efb",
    "color-social-google": "#4285f4",
    "color-checkbox-inactive": CoreColors["base08"],
    "color-background-section-info": CoreColors["info01"],
    "color-background-timeline": CoreColors["base03"],
    "color-background-section-primary2": CoreColors["primary02"],
    "color-background-OTP": CoreColors["info02"],
    "color-text-warning-2": CoreColors["warning04"],
};


export default Colors;